from __future__ import annotations

from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from motis_shared.types import Exchange, OrderSide, OrderType


class Order(BaseModel):
    """An order generated by an operator."""

    id: UUID = Field(default_factory=uuid4)
    operator_id: UUID
    user_id: UUID
    exchange: Exchange
    symbol: str
    side: OrderSide
    order_type: OrderType
    size: float
    price: Optional[float] = None          # None for market orders
    stop_price: Optional[float] = None
    reduce_only: bool = False
    client_order_id: str = Field(default_factory=lambda: str(uuid4()))
    created_at: datetime = Field(default_factory=datetime.utcnow)


class TradeLog(BaseModel):
    """
    Immutable record of a completed fill.
    Populated by the exchange-sync job from actual fill confirmations.
    Never written by operator code directly.
    """

    id: UUID = Field(default_factory=uuid4)
    operator_id: UUID
    user_id: UUID
    exchange: Exchange
    symbol: str
    side: OrderSide
    size: float
    entry_price: float
    fill_price: float
    fill_at: datetime
    fee: float
    fee_currency: str
    pnl: Optional[float] = None           # Realized PnL for closing trades
    exchange_order_id: str                 # Exchange's native order ID
    verified_at: Optional[datetime] = None # When platform verified against exchange API
    is_paper: bool = False


class Position(BaseModel):
    """Current open position for an operator."""

    operator_id: UUID
    symbol: str
    exchange: Exchange
    size: float                            # Positive = long, negative = short
    avg_entry_price: float
    current_price: Optional[float] = None
    unrealized_pnl: Optional[float] = None
    unrealized_pnl_pct: Optional[float] = None
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class PerformanceMetrics(BaseModel):
    """Computed performance stats (used by marketplace verification pipeline)."""

    operator_id: UUID
    period_days: int
    total_return_pct: float
    sharpe_ratio: Optional[float] = None
    sortino_ratio: Optional[float] = None
    max_drawdown_pct: float
    win_rate_pct: float
    total_trades: int
    avg_holding_period_hours: float
    calmar_ratio: Optional[float] = None
    computed_at: datetime = Field(default_factory=datetime.utcnow)
    verified: bool = False                 # True = platform cross-checked with exchange
