"""Initial schema — all Motis tables

Revision ID: 0001
Revises: 
Create Date: 2026-04-10

Hand-crafted (not autogenerated) to include:
  - GENERATED ALWAYS AS tsvector column on agent_memories (requires raw SQL)
  - GIN index on tsvector (requires raw SQL)
  - All other tables mirror the ORM models in db/models.py

Run with:
  alembic upgrade head

Rollback with:
  alembic downgrade -1
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | tuple | None = None
depends_on: str | tuple | None = None


def upgrade() -> None:
    # ── users ─────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("display_name", sa.String(100), nullable=True),
        sa.Column("avatar_url", sa.Text, nullable=True),
        sa.Column("role", sa.String(32), nullable=False, server_default="user"),
        # BYOM model config (encrypted)
        sa.Column("model_base_url_enc", sa.Text, nullable=True),
        sa.Column("model_api_key_enc", sa.Text, nullable=True),
        sa.Column("model_name", sa.String(120), nullable=True),
        sa.Column("model_reference_models", sa.Text, nullable=True),
        sa.Column("use_platform_model", sa.Boolean, nullable=False, server_default="true"),
        # Billing
        sa.Column("stripe_customer_id", sa.String(64), nullable=True),
        sa.Column("subscription_tier", sa.String(32), nullable=False, server_default="free"),
        sa.Column("feature_flags", postgresql.JSONB, nullable=False, server_default="{}"),
        # Timestamps
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_stripe", "users", ["stripe_customer_id"], unique=True, postgresql_where=sa.text("stripe_customer_id IS NOT NULL"))

    # ── exchange_connections ──────────────────────────────────────────────────
    op.create_table(
        "exchange_connections",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("exchange", sa.String(32), nullable=False),
        sa.Column("label", sa.String(64), nullable=False, server_default="default"),
        sa.Column("api_key_enc", sa.Text, nullable=False),
        sa.Column("api_secret_enc", sa.Text, nullable=False),
        sa.Column("api_passphrase_enc", sa.Text, nullable=True),
        sa.Column("is_testnet", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("user_id", "exchange", "label", name="uq_exchange_connection"),
    )
    op.create_index("ix_exchange_connections_user", "exchange_connections", ["user_id"])

    # ── agent_memories ────────────────────────────────────────────────────────
    # Cannot use op.create_table for GENERATED column — use raw DDL
    op.execute("""
        CREATE TABLE agent_memories (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            content     TEXT NOT NULL,
            type        TEXT NOT NULL DEFAULT 'general',
            tags        TEXT[] NOT NULL DEFAULT '{}',
            source      TEXT NOT NULL DEFAULT 'agent',
            importance  SMALLINT NOT NULL DEFAULT 5
                        CONSTRAINT importance_range CHECK (importance BETWEEN 1 AND 10),
            ts_vector   TSVECTOR
                        GENERATED ALWAYS AS (to_tsvector('english', content)) STORED,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("CREATE INDEX ix_agent_memories_user_id ON agent_memories(user_id)")
    op.execute("CREATE INDEX ix_agent_memories_fts ON agent_memories USING GIN(ts_vector)")
    op.execute("CREATE INDEX ix_agent_memories_type ON agent_memories(user_id, type)")

    # ── conversations ─────────────────────────────────────────────────────────
    op.create_table(
        "conversations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("title", sa.String(255), nullable=True),
        sa.Column("message_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_conversations_user_id", "conversations", ["user_id"])

    # ── conversation_messages ─────────────────────────────────────────────────
    op.create_table(
        "conversation_messages",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("role", sa.String(16), nullable=False),
        sa.Column("content", sa.Text, nullable=True),
        sa.Column("tool_calls", postgresql.JSONB, nullable=True),
        sa.Column("tool_call_id", sa.String(64), nullable=True),
        sa.Column("sequence", sa.Integer, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_conv_msg_convo_seq", "conversation_messages", ["conversation_id", "sequence"])

    # ── operators ─────────────────────────────────────────────────────────────
    op.create_table(
        "operators",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column("state", sa.String(32), nullable=False, server_default="draft"),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        sa.Column("operator_type", sa.String(32), nullable=False),
        sa.Column("asset_class", sa.String(32), nullable=False),
        sa.Column("strategy_style", sa.String(32), nullable=True),
        sa.Column("asset_universe", postgresql.ARRAY(sa.Text), nullable=False, server_default="{}"),
        sa.Column("exchange", sa.String(32), nullable=True),
        sa.Column("risk_config", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("trigger_config", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("model_config_override", postgresql.JSONB, nullable=True),
        sa.Column("graph_spec_url", sa.Text, nullable=True),
        sa.Column("graph_code", sa.Text, nullable=True),
        sa.Column("exchange_connection_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("exchange_connections.id", ondelete="SET NULL"), nullable=True),
        sa.Column("allocated_capital_usd", sa.Float, nullable=True),
        # Performance cache
        sa.Column("cached_pnl_pct", sa.Float, nullable=True),
        sa.Column("cached_pnl_usd", sa.Float, nullable=True),
        sa.Column("cached_sharpe", sa.Float, nullable=True),
        sa.Column("cached_max_dd_pct", sa.Float, nullable=True),
        sa.Column("metrics_computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report_url", sa.Text, nullable=True),
        sa.Column("source_listing_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_operators_user_id", "operators", ["user_id"])
    op.create_index("ix_operators_state", "operators", ["state"])

    # ── operator_run_logs ─────────────────────────────────────────────────────
    op.create_table(
        "operator_run_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("operator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("operators.id", ondelete="CASCADE"), nullable=False),
        sa.Column("node_name", sa.String(64), nullable=False),
        sa.Column("level", sa.String(16), nullable=False, server_default="info"),
        sa.Column("message", sa.Text, nullable=False),
        sa.Column("data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_run_logs_operator_created", "operator_run_logs", ["operator_id", "created_at"])

    # ── orders ────────────────────────────────────────────────────────────────
    op.create_table(
        "orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("operator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("operators.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("exchange", sa.String(32), nullable=False),
        sa.Column("symbol", sa.String(32), nullable=False),
        sa.Column("side", sa.String(8), nullable=False),
        sa.Column("order_type", sa.String(16), nullable=False),
        sa.Column("size", sa.Float, nullable=False),
        sa.Column("price", sa.Float, nullable=True),
        sa.Column("stop_price", sa.Float, nullable=True),
        sa.Column("reduce_only", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_paper", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("client_order_id", sa.String(64), nullable=False, unique=True),
        sa.Column("exchange_order_id", sa.String(128), nullable=True),
        sa.Column("status", sa.String(32), nullable=False, server_default="pending"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_orders_operator", "orders", ["operator_id"])
    op.create_index("ix_orders_user", "orders", ["user_id"])

    # ── trade_logs ────────────────────────────────────────────────────────────
    op.create_table(
        "trade_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("orders.id", ondelete="SET NULL"), nullable=True, unique=True),
        sa.Column("operator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("operators.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("exchange", sa.String(32), nullable=False),
        sa.Column("symbol", sa.String(32), nullable=False),
        sa.Column("side", sa.String(8), nullable=False),
        sa.Column("size", sa.Float, nullable=False),
        sa.Column("entry_price", sa.Float, nullable=True),
        sa.Column("fill_price", sa.Float, nullable=False),
        sa.Column("fill_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fee", sa.Float, nullable=False, server_default="0"),
        sa.Column("fee_currency", sa.String(16), nullable=False),
        sa.Column("pnl", sa.Float, nullable=True),
        sa.Column("exchange_order_id", sa.String(128), nullable=False),
        sa.Column("is_paper", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_trade_logs_operator_fill", "trade_logs", ["operator_id", "fill_at"])
    op.create_index("ix_trade_logs_user_fill", "trade_logs", ["user_id", "fill_at"])

    # ── positions ─────────────────────────────────────────────────────────────
    op.create_table(
        "positions",
        sa.Column("operator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("operators.id", ondelete="CASCADE"), nullable=False),
        sa.Column("symbol", sa.String(32), nullable=False),
        sa.Column("exchange", sa.String(32), nullable=False),
        sa.Column("size", sa.Float, nullable=False),
        sa.Column("avg_entry_price", sa.Float, nullable=False),
        sa.Column("current_price", sa.Float, nullable=True),
        sa.Column("unrealized_pnl", sa.Float, nullable=True),
        sa.Column("unrealized_pnl_pct", sa.Float, nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("operator_id", "symbol", "exchange"),
    )

    # ── operator_performance_metrics ──────────────────────────────────────────
    op.create_table(
        "operator_performance_metrics",
        sa.Column("operator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("operators.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("period_days", sa.Integer, nullable=False),
        sa.Column("total_return_pct", sa.Float, nullable=False),
        sa.Column("sharpe_ratio", sa.Float, nullable=True),
        sa.Column("sortino_ratio", sa.Float, nullable=True),
        sa.Column("max_drawdown_pct", sa.Float, nullable=False),
        sa.Column("win_rate_pct", sa.Float, nullable=False),
        sa.Column("total_trades", sa.Integer, nullable=False),
        sa.Column("avg_holding_period_hours", sa.Float, nullable=False),
        sa.Column("calmar_ratio", sa.Float, nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("verified", sa.Boolean, nullable=False, server_default="false"),
    )

    # ── marketplace_listings ──────────────────────────────────────────────────
    op.create_table(
        "marketplace_listings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("operator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("operators.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("creator_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="pending_review"),
        sa.Column("title", sa.String(120), nullable=False),
        sa.Column("tagline", sa.String(280), nullable=False),
        sa.Column("description_md", sa.Text, nullable=False),
        sa.Column("research_brief_url", sa.Text, nullable=True),
        sa.Column("price_monthly_usd", sa.Float, nullable=False),
        sa.Column("fee_pct", sa.Float, nullable=False, server_default="0.20"),
        sa.Column("subscriber_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_marketplace_listings_status", "marketplace_listings", ["status"])
    op.create_index("ix_marketplace_listings_creator", "marketplace_listings", ["creator_user_id"])

    # ── subscriptions ─────────────────────────────────────────────────────────
    op.create_table(
        "subscriptions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("listing_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("marketplace_listings.id", ondelete="CASCADE"), nullable=False),
        sa.Column("operator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("operators.id", ondelete="SET NULL"), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(64), nullable=True, unique=True),
        sa.Column("billing_status", sa.String(32), nullable=False, server_default="trial"),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("user_id", "listing_id", name="uq_subscription"),
    )
    op.create_index("ix_subscriptions_user", "subscriptions", ["user_id"])
    op.create_index("ix_subscriptions_listing", "subscriptions", ["listing_id"])

    # ── competitions ──────────────────────────────────────────────────────────
    op.create_table(
        "competitions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("title", sa.String(120), nullable=False),
        sa.Column("description_md", sa.Text, nullable=True),
        sa.Column("status", sa.String(32), nullable=False, server_default="upcoming"),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("allowed_asset_classes", postgresql.ARRAY(sa.Text), nullable=False, server_default="{}"),
        sa.Column("starting_capital_usd", sa.Float, nullable=False),
        sa.Column("max_leverage", sa.Float, nullable=False, server_default="3.0"),
        sa.Column("max_entries_per_user", sa.Integer, nullable=False, server_default="1"),
        sa.Column("prize_pool_usd", sa.Float, nullable=True),
        sa.Column("prize_description", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_competitions_status", "competitions", ["status"])

    # ── competition_entries ───────────────────────────────────────────────────
    op.create_table(
        "competition_entries",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("competition_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("competitions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("operator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("operators.id", ondelete="CASCADE"), nullable=False),
        sa.Column("rank", sa.Integer, nullable=True),
        sa.Column("total_return_pct", sa.Float, nullable=True),
        sa.Column("max_drawdown_pct", sa.Float, nullable=True),
        sa.Column("sharpe_ratio", sa.Float, nullable=True),
        sa.Column("disqualified", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("disqualification_reason", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("competition_id", "operator_id", name="uq_competition_entry"),
    )
    op.create_index("ix_competition_entries_comp", "competition_entries", ["competition_id"])
    op.create_index("ix_competition_entries_user", "competition_entries", ["user_id"])

    # ── competition_snapshots ─────────────────────────────────────────────────
    op.create_table(
        "competition_snapshots",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("entry_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("competition_entries.id", ondelete="CASCADE"), nullable=False),
        sa.Column("snapshot_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("portfolio_value_usd", sa.Float, nullable=False),
        sa.Column("daily_return_pct", sa.Float, nullable=False),
        sa.Column("cumulative_return_pct", sa.Float, nullable=False),
        sa.Column("rank_at_snapshot", sa.Integer, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("entry_id", "snapshot_date", name="uq_snapshot_entry_date"),
    )
    op.create_index("ix_competition_snapshots_entry", "competition_snapshots", ["entry_id"])

    # ── updated_at triggers ───────────────────────────────────────────────────
    # PostgreSQL trigger function to auto-update updated_at on UPDATE
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ language 'plpgsql';
    """)

    # Apply trigger to all tables with updated_at
    _tables_with_updated_at = [
        "users", "exchange_connections", "conversations",
        "operators", "subscriptions", "marketplace_listings",
        "competition_entries", "competitions",
    ]
    for table in _tables_with_updated_at:
        op.execute(f"""
            CREATE TRIGGER trig_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
        """)

    # ── agent_memories updated_at trigger ─────────────────────────────────────
    op.execute("""
        CREATE TRIGGER trig_agent_memories_updated_at
        BEFORE UPDATE ON agent_memories
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    """)


def downgrade() -> None:
    # Drop in reverse FK dependency order

    # Drop triggers first
    _tables_with_triggers = [
        "users", "exchange_connections", "conversations",
        "operators", "subscriptions", "marketplace_listings",
        "competition_entries", "competitions", "agent_memories",
    ]
    for table in _tables_with_triggers:
        op.execute(f"DROP TRIGGER IF EXISTS trig_{table}_updated_at ON {table}")

    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column()")

    # Drop tables in reverse dependency order
    op.drop_table("competition_snapshots")
    op.drop_table("competition_entries")
    op.drop_table("competitions")
    op.drop_table("subscriptions")
    op.drop_table("marketplace_listings")
    op.drop_table("operator_performance_metrics")
    op.drop_table("positions")
    op.drop_table("trade_logs")
    op.drop_table("orders")
    op.drop_table("operator_run_logs")
    op.drop_table("operators")
    op.drop_table("conversation_messages")
    op.drop_table("conversations")
    op.drop_table("agent_memories")
    op.drop_table("exchange_connections")
    op.drop_table("users")
