from __future__ import annotations

from typing import Annotated, Any, Optional
from typing_extensions import TypedDict

from langgraph.graph import add_messages
from pydantic import BaseModel


class SignalDirection:
    LONG = "long"
    SHORT = "short"
    FLAT = "flat"  # Exit / no position
    HOLD = "hold"  # Do nothing this tick


class Signal(BaseModel):
    """A trade signal generated by a reasoning node."""

    symbol: str
    direction: str  # SignalDirection
    confidence: float  # 0.0 – 1.0
    reasoning: str
    suggested_size_pct: Optional[float] = None  # % of operator capital
    suggested_entry: Optional[float] = None
    suggested_sl: Optional[float] = None
    suggested_tp: Optional[float] = None


class RiskResult(BaseModel):
    """Output of the risk_check node."""

    approved: bool
    approved_signals: list[Signal]
    rejected_signals: list[Signal]
    rejection_reasons: list[str]
    daily_pnl_usd: float
    open_position_count: int


class OperatorRunLog(BaseModel):
    """Single log entry from an operator tick."""

    tick_id: str
    node_name: str
    message: str
    data: Optional[dict] = None


class BaseOperatorState(TypedDict):
    """
    Minimum state fields shared by all operators.
    Subclasses extend this with their own fields.
    """

    # Market context
    market_data: dict[str, Any]          # OHLCV + orderbook keyed by symbol
    funding_rates: dict[str, float]      # symbol → current funding rate

    # Signal pipeline
    signals: list[Signal]
    risk_result: Optional[RiskResult]

    # Execution tracking
    pending_orders: list[dict]
    filled_orders: list[dict]
    open_positions: list[dict]
    daily_pnl_usd: float

    # Observability — streamed to frontend in real-time
    run_log: list[OperatorRunLog]

    # Control flow
    should_exit: bool                    # Set to True to terminate this tick early
