"""
Motis SQLAlchemy ORM — All Tables
==================================
Single source of truth for the database schema.
Alembic autogenerates migrations from these models.

Table inventory:
  Core auth:
    users                — accounts, BYOM config, platform role
    exchange_connections — encrypted exchange API keys per user

  Agent:
    agent_memories       — per-user long-term memory (FTS via tsvector)
    conversations        — conversation sessions
    conversation_messages— individual messages within a conversation

  Operators:
    operators            — operator definitions (strategy spec, risk config)
    operator_run_logs    — per-tick execution logs

  Trading:
    orders               — orders generated by operators
    trade_logs           — immutable fill records (cross-checked with exchange)
    positions            — current open positions per operator

  Marketplace:
    marketplace_listings — operator marketplace listings
    subscriptions        — user → listing subscriptions

  Arena:
    competitions         — trading competitions
    competition_entries  — operator enrolled in competition
    competition_snapshots— daily P&L snapshots per entry

  Platform:
    operator_performance_metrics — computed Sharpe/DD/WR stats
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    ARRAY,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, relationship
from sqlalchemy.sql import func, text


class Base(DeclarativeBase):
    pass


def _uuid():
    return str(uuid.uuid4())


# ── Timestamps mixin ──────────────────────────────────────────────────────────

class TimestampMixin:
    created_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


# ═══════════════════════════════════════════════════════════════════════════════
# CORE AUTH
# ═══════════════════════════════════════════════════════════════════════════════

class User(TimestampMixin, Base):
    """
    Platform user account.
    JWT auth is stateless — this table stores profile + model config.
    Auth itself (password hashing) is handled by the auth provider (Supabase / custom).
    """
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String(320), unique=True, nullable=False, index=True)
    display_name = Column(String(100), nullable=True)
    avatar_url = Column(Text, nullable=True)

    # Platform role: 'user' | 'operator_creator' | 'admin'
    role = Column(String(32), nullable=False, server_default="user")

    # BYOM — Bring Your Own Model config (encrypted at rest)
    # Encrypted via Fernet using ENCRYPTION_KEY env var
    model_base_url_enc = Column(Text, nullable=True)
    model_api_key_enc = Column(Text, nullable=True)
    model_name = Column(String(120), nullable=True)
    # Comma-separated additional model names for MoA
    model_reference_models = Column(Text, nullable=True)

    # Platform defaults (used when user hasn't configured BYOM)
    use_platform_model = Column(Boolean, nullable=False, server_default="true")

    # Billing
    stripe_customer_id = Column(String(64), nullable=True, unique=True)
    subscription_tier = Column(String(32), nullable=False, server_default="free")

    # Feature flags per user (overrides)
    feature_flags = Column(JSONB, nullable=False, server_default="{}")

    # Relationships
    exchange_connections = relationship("ExchangeConnection", back_populates="user", cascade="all, delete-orphan")
    operators = relationship("Operator", back_populates="user", cascade="all, delete-orphan")
    memories = relationship("AgentMemory", back_populates="user", cascade="all, delete-orphan")
    conversations = relationship("Conversation", back_populates="user", cascade="all, delete-orphan")


class ExchangeConnection(TimestampMixin, Base):
    """
    Encrypted exchange API key for a user.
    API key never leaves this table unencrypted — decrypted at MCP layer only.
    """
    __tablename__ = "exchange_connections"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    exchange = Column(String(32), nullable=False)   # Exchange enum value
    label = Column(String(64), nullable=False, server_default="default")

    # Encrypted credentials (Fernet)
    api_key_enc = Column(Text, nullable=False)
    api_secret_enc = Column(Text, nullable=False)
    api_passphrase_enc = Column(Text, nullable=True)  # OKX / some exchanges require this

    # Testnet vs mainnet
    is_testnet = Column(Boolean, nullable=False, server_default="false")

    # Verified: platform has confirmed the key works
    verified_at = Column(DateTime(timezone=True), nullable=True)
    last_sync_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    user = relationship("User", back_populates="exchange_connections")

    __table_args__ = (
        UniqueConstraint("user_id", "exchange", "label", name="uq_exchange_connection"),
    )


# ═══════════════════════════════════════════════════════════════════════════════
# AGENT MEMORY
# ═══════════════════════════════════════════════════════════════════════════════

class AgentMemory(TimestampMixin, Base):
    """
    Per-user long-term memory store.
    Replaces Hermes's SQLite/filesystem MEMORY.md.
    FTS via ts_vector GENERATED column (PostgreSQL 12+).
    """
    __tablename__ = "agent_memories"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)

    content = Column(Text, nullable=False)
    # 'general' | 'strategy' | 'risk_pref' | 'agent_insight' | 'operator_note'
    type = Column(String(32), nullable=False, server_default="general")
    tags = Column(ARRAY(Text), nullable=False, server_default="{}")
    source = Column(String(32), nullable=False, server_default="agent")  # 'agent' | 'user' | 'operator'
    # 1 (low) – 10 (high). Used to rank memories in context block.
    importance = Column(SmallInteger, nullable=False, server_default="5")

    # Relationships
    user = relationship("User", back_populates="memories")

    __table_args__ = (
        Index("ix_agent_memories_user_id", "user_id"),
        Index("ix_agent_memories_type", "user_id", "type"),
        # FTS index created in migration (GENERATED column + GIN index)
    )


# ═══════════════════════════════════════════════════════════════════════════════
# CONVERSATIONS
# ═══════════════════════════════════════════════════════════════════════════════

class Conversation(TimestampMixin, Base):
    """Chat session between user and the master agent."""
    __tablename__ = "conversations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    title = Column(String(255), nullable=True)   # Agent-generated title after first turn
    message_count = Column(Integer, nullable=False, server_default="0")

    # Relationships
    user = relationship("User", back_populates="conversations")
    messages = relationship("ConversationMessage", back_populates="conversation", cascade="all, delete-orphan")


class ConversationMessage(Base):
    """
    Individual message in a conversation.
    Stores role + content. Tool calls stored in tool_calls JSONB.
    NOT TimestampMixin — use created_at only (messages are immutable).
    """
    __tablename__ = "conversation_messages"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    conversation_id = Column(UUID(as_uuid=True), ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False, index=True)
    # 'user' | 'assistant' | 'tool'
    role = Column(String(16), nullable=False)
    content = Column(Text, nullable=True)
    # OpenAI tool_calls array if role='assistant', tool_call_id if role='tool'
    tool_calls = Column(JSONB, nullable=True)
    tool_call_id = Column(String(64), nullable=True)
    # Position in conversation
    sequence = Column(Integer, nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    # Relationships
    conversation = relationship("Conversation", back_populates="messages")

    __table_args__ = (
        Index("ix_conv_msg_convo_seq", "conversation_id", "sequence"),
    )


# ═══════════════════════════════════════════════════════════════════════════════
# OPERATORS
# ═══════════════════════════════════════════════════════════════════════════════

class Operator(TimestampMixin, Base):
    """
    A trading strategy or research/backtest operator.
    Maps 1:1 to Pydantic OperatorModel in shared package.
    """
    __tablename__ = "operators"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    name = Column(String(120), nullable=False)
    description = Column(Text, nullable=False, server_default="")

    # 'draft' | 'backtested' | 'paper' | 'live' | 'paused' | 'archived' | 'complete'
    state = Column(String(32), nullable=False, server_default="draft", index=True)
    version = Column(Integer, nullable=False, server_default="1")

    # 'live_trade' | 'paper_trade' | 'backtest' | 'research'
    operator_type = Column(String(32), nullable=False)

    # Strategy metadata (denormalised for fast listing queries)
    asset_class = Column(String(32), nullable=False)
    strategy_style = Column(String(32), nullable=True)
    asset_universe = Column(ARRAY(Text), nullable=False, server_default="{}")
    exchange = Column(String(32), nullable=True)

    # Full config stored as JSONB (risk_config, trigger_config, model_config_override)
    risk_config = Column(JSONB, nullable=False, server_default="{}")
    trigger_config = Column(JSONB, nullable=False, server_default="{}")
    model_config_override = Column(JSONB, nullable=True)

    # Operator graph stored externally (S3/R2) — URL reference only
    graph_spec_url = Column(Text, nullable=True)

    # Raw LangGraph code stored inline for small operators (< 64KB)
    graph_code = Column(Text, nullable=True)

    # Linked exchange connection (for live operators)
    exchange_connection_id = Column(UUID(as_uuid=True), ForeignKey("exchange_connections.id", ondelete="SET NULL"), nullable=True)

    # Capital allocation
    allocated_capital_usd = Column(Float, nullable=True)

    # Performance cache (updated by async compute job)
    cached_pnl_pct = Column(Float, nullable=True)
    cached_pnl_usd = Column(Float, nullable=True)
    cached_sharpe = Column(Float, nullable=True)
    cached_max_dd_pct = Column(Float, nullable=True)
    metrics_computed_at = Column(DateTime(timezone=True), nullable=True)

    # For ResearchOperator: S3 URL to the completed brief PDF/MD
    report_url = Column(Text, nullable=True)

    # Marketplace: if this operator is a clone from a listing
    source_listing_id = Column(UUID(as_uuid=True), nullable=True)

    # Relationships
    user = relationship("User", back_populates="operators")
    run_logs = relationship("OperatorRunLog", back_populates="operator", cascade="all, delete-orphan")
    orders = relationship("Order", back_populates="operator")
    performance_metrics = relationship("OperatorPerformanceMetrics", back_populates="operator", uselist=False, cascade="all, delete-orphan")


class OperatorRunLog(Base):
    """
    Per-tick execution log for an operator.
    Immutable — never updated, only appended.
    """
    __tablename__ = "operator_run_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    operator_id = Column(UUID(as_uuid=True), ForeignKey("operators.id", ondelete="CASCADE"), nullable=False, index=True)
    # LangGraph node that produced this log
    node_name = Column(String(64), nullable=False)
    # 'info' | 'warning' | 'error' | 'signal' | 'order' | 'fill'
    level = Column(String(16), nullable=False, server_default="info")
    message = Column(Text, nullable=False)
    data = Column(JSONB, nullable=True)  # Structured payload (e.g. signal details)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    # Relationships
    operator = relationship("Operator", back_populates="run_logs")

    __table_args__ = (
        Index("ix_run_logs_operator_created", "operator_id", "created_at"),
    )


# ═══════════════════════════════════════════════════════════════════════════════
# TRADING
# ═══════════════════════════════════════════════════════════════════════════════

class Order(TimestampMixin, Base):
    """Order generated by an operator. May or may not be filled."""
    __tablename__ = "orders"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    operator_id = Column(UUID(as_uuid=True), ForeignKey("operators.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    exchange = Column(String(32), nullable=False)
    symbol = Column(String(32), nullable=False)
    side = Column(String(8), nullable=False)         # 'buy' | 'sell'
    order_type = Column(String(16), nullable=False)  # 'market' | 'limit' | 'stop_market' | 'stop_limit'
    size = Column(Float, nullable=False)
    price = Column(Float, nullable=True)             # None for market orders
    stop_price = Column(Float, nullable=True)
    reduce_only = Column(Boolean, nullable=False, server_default="false")
    is_paper = Column(Boolean, nullable=False, server_default="false")
    client_order_id = Column(String(64), unique=True, nullable=False)

    # Exchange-side status
    exchange_order_id = Column(String(128), nullable=True)
    status = Column(String(32), nullable=False, server_default="pending")  # pending|submitted|filled|cancelled|rejected

    # Relationships
    operator = relationship("Operator", back_populates="orders")
    fill = relationship("TradeLog", back_populates="order", uselist=False)


class TradeLog(Base):
    """Immutable fill record. Written by exchange-sync job from confirmed fills."""
    __tablename__ = "trade_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    order_id = Column(UUID(as_uuid=True), ForeignKey("orders.id", ondelete="SET NULL"), nullable=True, unique=True)
    operator_id = Column(UUID(as_uuid=True), ForeignKey("operators.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    exchange = Column(String(32), nullable=False)
    symbol = Column(String(32), nullable=False)
    side = Column(String(8), nullable=False)
    size = Column(Float, nullable=False)
    entry_price = Column(Float, nullable=True)    # None for closing trades
    fill_price = Column(Float, nullable=False)
    fill_at = Column(DateTime(timezone=True), nullable=False)
    fee = Column(Float, nullable=False, server_default="0")
    fee_currency = Column(String(16), nullable=False)
    pnl = Column(Float, nullable=True)            # Realized PnL for closing trades
    exchange_order_id = Column(String(128), nullable=False)
    is_paper = Column(Boolean, nullable=False, server_default="false")
    verified_at = Column(DateTime(timezone=True), nullable=True)

    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    # Relationships
    order = relationship("Order", back_populates="fill")

    __table_args__ = (
        Index("ix_trade_logs_operator_fill", "operator_id", "fill_at"),
        Index("ix_trade_logs_user_fill", "user_id", "fill_at"),
    )


class Position(Base):
    """Current open position for an operator on an exchange."""
    __tablename__ = "positions"

    operator_id = Column(UUID(as_uuid=True), ForeignKey("operators.id", ondelete="CASCADE"), nullable=False)
    symbol = Column(String(32), nullable=False)
    exchange = Column(String(32), nullable=False)

    size = Column(Float, nullable=False)           # Positive = long, negative = short
    avg_entry_price = Column(Float, nullable=False)
    current_price = Column(Float, nullable=True)
    unrealized_pnl = Column(Float, nullable=True)
    unrealized_pnl_pct = Column(Float, nullable=True)
    updated_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now())

    __table_args__ = (
        # Composite PK: one position record per (operator, symbol, exchange)
        __import__("sqlalchemy").PrimaryKeyConstraint("operator_id", "symbol", "exchange"),
    )


# ═══════════════════════════════════════════════════════════════════════════════
# PERFORMANCE METRICS
# ═══════════════════════════════════════════════════════════════════════════════

class OperatorPerformanceMetrics(Base):
    """
    Computed performance stats. One record per operator (upserted by compute job).
    verified=True means platform cross-checked fills against exchange API.
    """
    __tablename__ = "operator_performance_metrics"

    operator_id = Column(UUID(as_uuid=True), ForeignKey("operators.id", ondelete="CASCADE"), primary_key=True)
    period_days = Column(Integer, nullable=False)
    total_return_pct = Column(Float, nullable=False)
    sharpe_ratio = Column(Float, nullable=True)
    sortino_ratio = Column(Float, nullable=True)
    max_drawdown_pct = Column(Float, nullable=False)
    win_rate_pct = Column(Float, nullable=False)
    total_trades = Column(Integer, nullable=False)
    avg_holding_period_hours = Column(Float, nullable=False)
    calmar_ratio = Column(Float, nullable=True)
    computed_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    verified = Column(Boolean, nullable=False, server_default="false")

    # Relationships
    operator = relationship("Operator", back_populates="performance_metrics")


# ═══════════════════════════════════════════════════════════════════════════════
# MARKETPLACE
# ═══════════════════════════════════════════════════════════════════════════════

class MarketplaceListing(TimestampMixin, Base):
    """An operator listed on the Motis marketplace."""
    __tablename__ = "marketplace_listings"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    operator_id = Column(UUID(as_uuid=True), ForeignKey("operators.id", ondelete="CASCADE"), nullable=False, unique=True)
    creator_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # 'pending_review' | 'live' | 'suspended' | 'delisted'
    status = Column(String(32), nullable=False, server_default="pending_review", index=True)

    # Listing content
    title = Column(String(120), nullable=False)
    tagline = Column(String(280), nullable=False)
    description_md = Column(Text, nullable=False)
    research_brief_url = Column(Text, nullable=True)  # Link to ResearchOperator output

    # Pricing
    price_monthly_usd = Column(Float, nullable=False)
    # Creator receives (1 - fee_pct) of revenue
    fee_pct = Column(Float, nullable=False, server_default="0.20")

    # Subscriber count (denormalised cache)
    subscriber_count = Column(Integer, nullable=False, server_default="0")

    # Relationships
    subscriptions = relationship("Subscription", back_populates="listing", cascade="all, delete-orphan")


class Subscription(TimestampMixin, Base):
    """A user's subscription to a marketplace listing."""
    __tablename__ = "subscriptions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    listing_id = Column(UUID(as_uuid=True), ForeignKey("marketplace_listings.id", ondelete="CASCADE"), nullable=False, index=True)

    # Instantiated operator for this subscriber
    operator_id = Column(UUID(as_uuid=True), ForeignKey("operators.id", ondelete="SET NULL"), nullable=True)

    # Billing
    stripe_subscription_id = Column(String(64), nullable=True, unique=True)
    # 'active' | 'past_due' | 'cancelled' | 'trial'
    billing_status = Column(String(32), nullable=False, server_default="trial")
    current_period_end = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    listing = relationship("MarketplaceListing", back_populates="subscriptions")

    __table_args__ = (
        UniqueConstraint("user_id", "listing_id", name="uq_subscription"),
    )


# ═══════════════════════════════════════════════════════════════════════════════
# ARENA
# ═══════════════════════════════════════════════════════════════════════════════

class Competition(TimestampMixin, Base):
    """A trading competition on the Motis Arena."""
    __tablename__ = "competitions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title = Column(String(120), nullable=False)
    description_md = Column(Text, nullable=True)
    # 'upcoming' | 'registration' | 'live' | 'completed'
    status = Column(String(32), nullable=False, server_default="upcoming", index=True)

    # Rules
    start_at = Column(DateTime(timezone=True), nullable=False)
    end_at = Column(DateTime(timezone=True), nullable=False)
    allowed_asset_classes = Column(ARRAY(Text), nullable=False, server_default="{}")
    starting_capital_usd = Column(Float, nullable=False)
    max_leverage = Column(Float, nullable=False, server_default="3.0")
    max_entries_per_user = Column(Integer, nullable=False, server_default="1")

    # Prize
    prize_pool_usd = Column(Float, nullable=True)
    prize_description = Column(Text, nullable=True)

    # Relationships
    entries = relationship("CompetitionEntry", back_populates="competition", cascade="all, delete-orphan")


class CompetitionEntry(TimestampMixin, Base):
    """An operator enrolled in a competition."""
    __tablename__ = "competition_entries"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    competition_id = Column(UUID(as_uuid=True), ForeignKey("competitions.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    operator_id = Column(UUID(as_uuid=True), ForeignKey("operators.id", ondelete="CASCADE"), nullable=False)

    # Current rank (updated by leaderboard job)
    rank = Column(Integer, nullable=True)
    # Cumulative return % since competition start
    total_return_pct = Column(Float, nullable=True)
    max_drawdown_pct = Column(Float, nullable=True)
    sharpe_ratio = Column(Float, nullable=True)

    # Disqualified flag (rule violations)
    disqualified = Column(Boolean, nullable=False, server_default="false")
    disqualification_reason = Column(Text, nullable=True)

    # Relationships
    competition = relationship("Competition", back_populates="entries")
    snapshots = relationship("CompetitionSnapshot", back_populates="entry", cascade="all, delete-orphan")

    __table_args__ = (
        UniqueConstraint("competition_id", "operator_id", name="uq_competition_entry"),
    )


class CompetitionSnapshot(Base):
    """Daily P&L snapshot for a competition entry (leaderboard history)."""
    __tablename__ = "competition_snapshots"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    entry_id = Column(UUID(as_uuid=True), ForeignKey("competition_entries.id", ondelete="CASCADE"), nullable=False, index=True)
    snapshot_date = Column(DateTime(timezone=True), nullable=False)
    portfolio_value_usd = Column(Float, nullable=False)
    daily_return_pct = Column(Float, nullable=False)
    cumulative_return_pct = Column(Float, nullable=False)
    rank_at_snapshot = Column(Integer, nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    # Relationships
    entry = relationship("CompetitionEntry", back_populates="snapshots")

    __table_args__ = (
        UniqueConstraint("entry_id", "snapshot_date", name="uq_snapshot_entry_date"),
    )
